baseurl: "https://engineering.rakuten.today/"  # Include trailing slash
languageCode: "en-us"
title: "Rakuten Engineering Blog"
pygmentsstyle: 'monokai'
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
# TRACKING STARTS
googleAnalytics: 'G-Z6FNGN7J13'
privacy:
  googleAnalytics:
    respectDoNotTrack: true
    anonymizeIP: true
    useSessionStorage: true
# TRACKING ENDS
